deploy:
    stage: deploy
    script:
        - ~/.rbenv/versions/2.7.1/bin/bundle install
        - ~/.rbenv/versions/2.7.1/bin/bundle exec jekyll build
        - rm -rf /var/www/bierdoctor.com
        - mv _site /var/www/bierdoctor.com
        - restorecon -R -v /var/www/bierdoctor.com
