# Site wide configuration

title:            Emilee Rader
locale:           en_US
url:              


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Emilee Rader
  avatar: bio-photo.jpg
  bio: "Associate Professor @ the University of Wisconsin-Madison"
  cv: "/vita/vitaEJR.pdf"
  email: ejrader2@wisc.edu
